baseurl = "https://uniquedivinetravels-bt.com"
title = "Unique Divine Travels"
theme = "hugo-universal-theme"
languageCode = "en-us"
defaultContentLanguage = "en"
disqusShortname = ""
googleAnalytics = ""
summaryLength = 70
paginate = 10
pluralizelisttitles = false

# ---------------- MENU ----------------

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1


[[menu.main]]
    name       = "About Bhutan"
    identifier = "menu.About Bhutan"
    url        = "/img/Punakha-dzong.jpg"
    weight     = 3

[[menu.main]]
    name       = "Bhutan"
    identifier = "section.Bhutan"
    url        = ""
    weight     = 1
    parent     = "menu.About Bhutan"
    post       = 1

[[menu.main]]
    name       = "Destinations"
    identifier = "section.Destinations"
    url        = ""
    weight     = 2
    parent     = "menu.About Bhutan"
    post       = 2

[[menu.main]]
    name       = "History of Bhutan"
    url        = "/history_of_bhutan"
    weight     = 1
    parent     = "section.Bhutan"

[[menu.main]]
    name       = "Gross National Happiness (GNH)"
    url        = "/gross_national_happiness"
    weight     = 2
    parent     = "section.Bhutan"

[[menu.main]]
    name       = "Climate in Bhutan"
    url        = "/climate_in_bhutan"
    weight     = 3
    parent     = "section.Bhutan"

[[menu.main]]
    name       = "Festivals"
    url        = "/festivals"
    weight     = 4
    parent     = "section.Bhutan"

[[menu.main]]
    name       = "Culture & Traditions"
    url        = "/culture_and_traditions"
    weight     = 5
    parent     = "section.Bhutan"

[[menu.main]]
    name       = "Bhutan at a glance"
    url        = "/bhutan_at_a_glance"
    weight     = 6
    parent     = "section.Bhutan"
    

[[menu.main]]
    name       = "Thimphu"
    url        = "/thimphu"
    weight     = 1
    parent     = "section.Destinations"

[[menu.main]]
    name       = "Paro"
    url        = "/paro"
    weight     = 2
    parent     = "section.Destinations"

[[menu.main]]
    name       = "Bumthang"
    url        = "/bumthang"
    weight     = 3
    parent     = "section.Destinations"
    
[[menu.main]]
    name       = "Zhemgang"
    url        = "/zhemgang"
    weight     = 4
    parent     = "section.Destinations"
    
[[menu.main]]
    name       = "Punakha"
    url        = "/punakha"
    weight     = 5
    parent     = "section.Destinations"
    
[[menu.main]]
    name       = "Trongsa"
    url        = "/trongsa"
    weight     = 6
    parent     = "section.Destinations"
    
[[menu.main]]
    name       = "Wangdiphodrang"
    url        = "/wangdiphodrang"
    weight     = 7
    parent     = "section.Destinations"

[[menu.main]]
    name       = "Travel Guide"
    identifier = "menu.Travel Guide"
    url        = "/img/bhutan-airlines.jpg"
    weight     = 3

[[menu.main]]
    name       = "Planning Trip"
    identifier = "section.Planning Trip"
    url        = ""
    weight     = 1
    parent     = "menu.Travel Guide"
    post       = 1

[[menu.main]]
    name       = "VISA"
    url        = "/visa"
    weight     = 1
    parent     = "section.Planning Trip"

[[menu.main]]
    name       = "Tariff"
    url        = "/tariff"
    weight     = 2
    parent     = "section.Planning Trip"

[[menu.main]]
    name       = "Flight"
    url        = "/flight"
    weight     = 3
    parent     = "section.Planning Trip"

[[menu.main]]
    name       = "Accommodation"
    url        = "/accommodation"
    weight     = 4
    parent     = "section.Planning Trip"

[[menu.main]]
name = "Tour Packages"
identifier = "menu.tour-packages"
url = "#"
weight = 5

[[menu.main]]
name = "Cultural Tours"
url = "/cultural_tours"
parent = "menu.tour-packages"
weight = 1

[[menu.main]]
name = "Festival Tours"
url = "/festival_tours"
parent = "menu.tour-packages"
weight = 2

[[menu.main]]
name = "Community-based Ecotourism"
url = "/community-based_ecotourism"
parent = "menu.tour-packages"
weight = 3

[[menu.main]]
name = "Wildlife Tours"
url = "/wildlife_tours"
parent = "menu.tour-packages"
weight = 4

[[menu.main]]
name = "Special Tours"
url = "/special_tours"
parent = "menu.tour-packages"
weight = 5

[[menu.main]]
name = "About Us"
identifier = "menu.about-us"
url = "/about_us"
weight = 6

[[menu.main]]
name = "FAQ"
identifier = "menu.faq"
url = "/faq"
weight = 7

[[menu.main]]
identifier = "menu.contact"
name = "Contact"
url = "/contact/"
weight = 8

# -------- TOP BAR --------
[[menu.topbar]]
weight = 1
name = "Facebook"
url = "https://www.facebook.com"
pre = "<i class='fab fa-2x fa-facebook' style='color:#1877F2'></i>"

[[menu.topbar]]
weight = 2
name = "WhatsApp"
url = "https://whatsapp.com"
pre = "<i class='fab fa-2x fa-whatsapp' style='color:#25D366'></i>"

[[menu.topbar]]
weight = 3
name = "Instagram"
url = "https://www.instagram.com"
pre = "<i class='fab fa-2x fa-instagram' style='color:#E4405F'></i>"

[[menu.topbar]]
weight = 4
name = "Email"
url = "mailto:info@uniquedivinetravels-bt.com"
pre = "<i class='fas fa-2x fa-envelope' style='color:#FF4500'></i>"

# ---------------- PARAMS ----------------
[params]
viewMorePostLink = "/blog/"
author = ""

defaultKeywords = ["Bhutan tours", "Bhutan travel agency", "Bhutan tour packages", "Bhutan holidays", "Unique Divine Travels"]
defaultDescription = "Unique Divine Travels is a trusted Bhutan tour operator offering customized cultural tours, wildlife tours, trekking adventures, and holiday packages."

facebook_site = ""
twitter_site = "GoHugoIO"
default_sharing_image = "img/sharing-default.png"

enableGoogleMaps = false
googleMapsApiKey = ""
latitude = ""
longitude = ""
direction = ""

style = "blue"

formspree_action = "https://formspree.io/f/xeqbddyp"
contact_form_ajax = false

enableRecaptchaInContactForm = true
googleRecaptchaKey = "site_key_for_google_recaptcha"

about_us = "<p>Selfless quality services</p>"
copyright = "Copyright © 2026 Unique Divine Travels. All rights reserved."

date_format = "January 2, 2006"
dropdown_mouse_over = false
disabled_logo = false
logo_text = "Unique Divine Travels"
logo = "img/udt-logo.svg"
logo_small = "img/udt-logo.svg"
contact_url = "/contact"

address = """<p class="text-uppercase"><strong>Unique Divine Travels</strong>
<br>IT Park
<br>Babesa
<br>Thimphu
<strong>Bhutan</strong>
</p>"""

[permalinks]
blog = "/blog/:year/:month/:day/:filename/"

[params.topbar]
enable = true
text = """<p class="hidden-sm hidden-xs">
Contact us on Bhutan: +97577456292 | USA: +19179414374 or info@uniquedivinetravels-bt.com
</p>

<p class="hidden-md hidden-lg">
<a href="tel:+97577456292" title="Call Bhutan" style="margin-right:10px;">
📞 Bhutan
</a>

<a href="tel:+19179414374" title="Call USA" style="margin-right:10px;">
📞 USA
</a>

<a href="mailto:info@uniquedivinetravels-bt.com" title="Email">
✉️ Email
</a>
</p>
"""

[params.widgets]
categories = true
tags = true
search = true

[params.carouselCustomers]
items = 6
auto_play = false
slide_speed = 2000
pagination_speed = 1000

[params.carouselTestimonials]
items = 4
auto_play = false
slide_speed = 2000
pagination_speed = 1000

[params.carousellHomepage]
enable = false
auto_play = false

[params.features]
enable = true
cols = 2

[params.testimonials]
enable = true
title = "Services we provide"
subtitle = "Here are some of the services we provide."

[params.see_more]
enable = false
icon = "far fa-file-alt"
title = "Do you want to know more?"
subtitle = "Here are some quick glances of our services."
link_url = ""
link_text = "Check it out!"

[params.clients]
enable = true
title = ""
subtitle = "We are registered with the following organizations:"

[params.places_you_can_visit]
enable = false
title = "Places you can visit"
subtitle = "Bhutan, also known as the last shangri-la..."
hide_summary = false

[params.footer.recent_posts]
enable = true

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
