---
title: "Accomodation"
author: "lekdhen06"
date: "2023-11-08"
output: html_document
---

UD Travel ensures safe place and sound sleep of tourist after every tiring day imperatively. In this respect, we always arrange relaxed ambience for night halts according to the demand of tourists. Apart from facilitating ***Hotel Reservation***, we provide ***Home-Stay service*** in the village for reasonable price with an aim, not only for one time experience and entertainment but to embed cultivation of inter-relationship between host family and tourists through direct interaction and exchange of shared socio-cultural values.


Arranging night halts in designated **Campsites** with basic amenities is another service that we take into account very seriously besides healthy food menu.


UD travel ensures ***safe and reliable transport service*** despite undulating and narrow country roads. Our smooth and steady transport service is always expected to reach prescheduled day-to-day destinations in pursuit of fulfilling aspirations of respected tourists under the motivation of our selfless quality services.  
