---
title: "Cultural Tours"
author: "lekdhen06"
date: "2023-11-08"
output: html_document
---

**Cultural Tour Package**


**Season: March to May and September to December** 


***Day 1: Arrive in Paro***

-	Reception in the airport by Unique Divine Travels' guide and driver;
-	Visit Ta Dzong (watch tower) which has been currently transformed into   a fascinating museum that showcases Bhutanese rich art and artifacts;   and
-	night halt in hotel.


***Day 2: Local tour in Paro valley***

 -	Drive in the morning and walk to Paro Taktshang monastery (Tiger    Nest);
 -	Visit Kichu Lhakhang (temple) that dates back to 7th century; and
 -	Night halt in hotel.


***Day 3: Fly to Bumthang***

-	Visit Jampel Lhakhang (temple) dates back to 7th century, Tamshing      monastery, Kurjey Lhakhang (temple popular for body imprint of Guru     Rimpoche in the  cave);
-	Explore Chamkhar town; and
-	Night halt in hotel.


***Day 4: Village tour in Bumthang***

-	Visit Kharchu monastery that houses more than 400 monks; 
-	Visit Mebar Tsho (Burning Lake) a saint called Pema Lingpa unearthed    sacred treasure in 14th century;
-	Village walk in Ura, visit temple and School;
-	Drive back to Tangsibi village and visit local temple; and
-	Night halt at home stay (if preferred cultural dance will be arranged in the night).


***Day 5: Bumthang to Phobjikha via Trongsa***

-	Drive to Trongsa and visit Ta Dzong museum;
-	Drop by Chendebji chorten (popular stupa);and 
-	Continue the journey to Phobjikha crossing two majestic passes Pele La   and Lawa La. Occasional break or stop for pictures of awesome           landscapes; and
-	Night halt in hotel or home stay.


***Day 6: Phobjikha to Punakha***

-	Visit Black-necked Crane visitor center followed by Gangtey monastery   sits atop a knoll;
-	Visit to Wangduephodrang Dzong that is reconstructed after it was       ravaged by fire in 2012; 
-	Drive to Punakha and visit the Dzong charismatically situated in the    confluence of Pho Chhu (Male River) and Mo Chhu (Female River); and
-	Night halt in hotel.


***Day 7: Punakha to Thimphu***

-	Visit Chimi Lhakhang, a temple, popularly revered for human fertility   enrichment, is blessed by Lama Drukpa Kunley who was known as Divine     Madman; 
-	Stop at Botanical Park if time permits, and also stop at Dochu La       where there are 108 Chortens (stupas);  
-	In the evening you can visit Tashichodzong, the fortress that serves    as seats for government and monastic bodies; and
-	Stroll in Thimphu city.


***Day 8: Thimphu sightseeing***

-	In the morning drive to Tango monastery and rejoice the learning        environment of Buddha dharma; 
-	Drive back to Zorig Chusum where traditional thirteen arts and crafts   of Bhutan are being taught;
-	Visit Buddha Point where there sits a gigantic bronze statue of Buddha   Shakyamuni;
-	Visit Folk heritage museum;
-	If time permits, apart from cultural tour, you can visit Takin          preserve; and 
- Night halt in hotel at Thimphu

***Day 9: Depart from Paro*** 
