---
title: "Festival Tours"
author: "lekdhen06"
date: "2023-11-08"
output: html_document
---

**Festival Tour Package**


Festival tourism depends upon the dates of Bhutanese Lunar Calendar and therefore big festival like Tshechu across Bhutan will be on different dates and month mostly. However, Unique Divine Travels focused our festival tour on Jampel Lhakhang Tshechu which carries a paramount sacred values. 


**March to April and September through December**


***Day 1:	Arrive at Paro International Airport***

-	Reception in the airport by Unique Divine Travels' guide and driver;
-	Visit Ta Dzong (watch tower) which has been currently transformed into   a fascinating museum that showcases Bhutanese rich art and artifacts;   and
-	Night halt in hotel.


***Day 2:	Paro***

-	Trekking to Taktshang monastery (Tiger Nest); and
-	Visit Kichu and Dhungtsi Lhakhang if time permits.


***Day 3:	Paro to Bumthang***

-	Fly to Bumthang;
-	Visit Kurjey lhakhang temple), Tamshing and Kharchu monasteries; and
-	Stroll Chamkhar town.


***Day 4 and 5: Witness Jampel Lhakhang Tshechu***

-	Attend Jampel lhakhang Tshechhu that performs extraordinarily sacred    naked dance associated with mask dance and other cultural programs;
-	Stroll; and 
-	Night halt at hotel.


***Day 6: Chamkhar to Ura***

-	Visit Ura, Shinkhar and Tangsibi Lhakhang; and
-	Night halt at Tangsibi (home stay).


***Day 7:  Bumthang to Phobjikha***

-	Visit Gangtey monastery; 
-	Visit Black-necked crane information center and spot the globally       endangered bird using long range telescope; and 
-	Stroll the Phobjikha small town.


***Day 8:  Phobjikha to Thimphu***

-	Visit Chimi Lhakhang, a temple, popularly revered for human fertility   enrichment, is blessed by Lama Dukpa Kunley who was known as Divine     Madman;
-	Stop at Dochu La where there are 108 Chortens (stupas);  
-	In the evening you can visit Tashichodzong, the fortress that serves    as seats for government and monastic bodies; and
-	Stroll in Thimphu city.


***Day 9:	Sightseeing within Thimphu***

-	Drive to Zorig Chusum where traditional thirteen arts and crafts of     Bhutan are being taught;
-	Visit Buddha Point where there sits a gigantic bronze statue of Buddha   Shakyamuni;
-	Visit Folk heritage museum and Takin preserve; and 
-	Night halt in hotel at Thimphu.


***Day 10: Thimphu to Paro***
-	Depart from Paro
