---
title: "Special Tours"
author: "lekdhen06"
date: "2023-11-08"
output: html_document
---

**Special Tour Package (Adventurous and more exciting with a mixture of cultural and natural heritages)**


**Season: March to May and September through December**


***Day 1: Arrive at Paro international airport***

-	Reception at Paro airport by Unique Divine Travels' guide and driver;
-	Visit Ta Dzong (watch tower) which has been currently transformed into   a fascinating museum that showcases Bhutanese rich art and artifacts;   and
-	Night halt in hotel.


***Day 2:  Paro to Bumthang***

-	Fly to Bumthang; 
-	Biking between Latongla and Tharpaling; 
-	Explore Chamkhar town; and
-	Night halt in hotel or home stay.


***Day 3:  Trekking from Bumthang to Trongsa***

-	Trekking from Chumey (Bumthang) to Kunga Rabten, Trongsa (6 hours);     and
-	Night halt at Trongsa.


***Day 4:  Trongsa to Royal Manas National Park (RMNP), Zhemgang***

-	Drive to Royal Manas National Park;
-	Significant amount of wildlife sightings and panoramic views; and
-	Camp at Pantang.


***Day 5: Pantang to Panbang***

-	Drive to Panbang for rafting inside RMNP;
-	Explore the village and small town of Panbang;
-	Participate in local way of fishing in the evening; and 
-	Night halt at Panbang camp.


***Day 6: Panbang to Trongsa***

-	Visit Zhemgang Dzong on the way;
-	Stop occasionally for wildlife photography and scenic landscape; and 
-	Night halt at Trongsa.


***Day 7: Trongsa to Phobjikha, Wangdue***

-	Short trekking from Trongsa Dzong to view point;
-	Drop by Chendebji chorten (popular stupa); 
-	Continue the journey to Phobjikha crossing two majestic passes Pele La   and Lawa La. Occasional break or stop for pictures of awesome           landscape; and
-	Night halt in hotel or home stay.


***Day 8: Phobjikha to Punakha***

-	Visit Black-necked Crane visitor center followed by Gangtey monastery   sits atop a knoll;
-	Visit to Wangduephodrang Dzong that is reconstructed after it was       ravaged by fire in 2012; 
-	Drive to Punakha and visit the Dzong charismatically situated in the    confluence of Pho Chhu (Male River) and Mo Chhu (Female River); and
-	Night halt in hotel.


***Day 9: Punakha to Thimphu Dzongkhag***

-	Drive to Zorig Chusum where traditional thirteen arts and crafts of     Bhutan are being taught;
-	Visit Buddha Point where there sits a gigantic bronze statue of Buddha   Shakyamuni;
-	Visit Folk heritage museum;
-	Takin preserve; and 
-	Night halt in hotel at Thimphu.


***Day 10: Thimphu to Paro Dzongkhag***

-	Drive to Paro and trek to Taktshang; and
-	Stroll Paro town.


***Day 11: Depart from Paro*** 
