---
title: "Wildlife Tours"
author: "lekdhen06"
date: "2023-11-19"
output: html_document
---

**Wildlife Tour Package**


**Season: March to May and September to December**


***Day 1: Arrive at Paro***

-	Reception in the airport by Unique Divine Travels' gudie and driver;
-	Drive to Thimphu and if time permits go in Jigme Dorji National Park    for birding and wildlife sighting; 
-	Stroll Thimphu city in the evening; and 
-	Night halt in hotel.


***Day 2: Thimphu to Phobjikha***

-	Visit Lamperi Botanical Park on the way to Wangdue;
-	Probability of seeing gray langur between Dhungdhung Ngyelsa and Pele   La;
-	Continue towards Phobjikha, the winter roosting ground of globally      endangered Black-necked crane. Probability to see cranes is high in     November through February;
-	Visit Black-necked Crane Visitor Center; 
-	Sightseeing and photography in the valley of Phobjikha; and
-	Night halt in home-stay or hotel.


***Day 3: Drive to Trongsa and Bumthang***

-	On the way to Trongsa walk (optional) old trail for a hour and half     between viewpoint and Trongsa Dzong (fortress) in the interest of       wildlife sighting especially golden Langur (endangered), Himalayan      black bear, Sambar deer and birds;
-	Continue to Bumthang; and
-	Night halt in home-stay at Tangsibi.


***Day 4: Tangsibi to Phrumsengla National Park***

-	Visit park information center at Ura prior to entering the park;
-	Drive inside Phrumsengla National Park;
-	You will come across terrestrial pheasants along the highway also       often encountered goral, sambar deer, and musk deer;
-	Birding starts from Sengor to Yongkola (one of the best birding sites   in South east Asia) along the highway; and 
-	Night halts in home-stay or hotel or camping.


***Day 5: Birding in Phrumsengla National Park***

-	Continue birding inside the park along the highway; and 
-	Night halt in hotel or home-stay or camping.


***Day 6: Continue birding in Phrumsengla National Park and drive back to Bumthang***

-	Continue birding inside the park along the highway; and 
-	Night halt in hotel or home-stay.


***Day 7: Bumthang to Paro***

-	Fly to Paro in the morning and trek to Taktshang (tiger nest); and
-	Stroll Paro town in the evening.


***Day 8: Depart from Paro***

